/**
 * Shell completion script generators.
 *
 * Walks the Commander command tree at runtime and produces self-contained
 * completion scripts for bash, zsh, fish, and powershell.
 */

import type { Command, Option } from 'commander';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type Shell = 'bash' | 'zsh' | 'fish' | 'powershell';

export const SUPPORTED_SHELLS: readonly Shell[] = ['bash', 'zsh', 'fish', 'powershell'] as const;

interface OptionInfo {
  long: string;
  short?: string;
  description: string;
  takesArg: boolean;
}

interface SubcommandInfo {
  name: string;
  description: string;
}

interface CompletionNode {
  path: string[];
  description: string;
  options: OptionInfo[];
  subcommands: SubcommandInfo[];
}

// ---------------------------------------------------------------------------
// Tree walker
// ---------------------------------------------------------------------------

function extractOptions(cmd: Command): OptionInfo[] {
  return (cmd.options as Option[])
    .filter((o) => !(o as unknown as Record<string, boolean>).hidden)
    .map((o) => ({
      long: o.long ?? '',
      short: o.short ?? undefined,
      description: o.description ?? '',
      takesArg: !!(o.required || o.optional),
    }));
}

function walkCommandTree(program: Command): CompletionNode[] {
  const nodes: CompletionNode[] = [];

  function walk(cmd: Command, path: string[]): void {
    const visibleSubs = cmd.commands.filter(
      (c) => !(c as unknown as Record<string, boolean>)._hidden,
    );

    nodes.push({
      path,
      description: cmd.description() ?? '',
      options: extractOptions(cmd),
      subcommands: visibleSubs.map((c) => ({
        name: c.name(),
        description: c.description() ?? '',
      })),
    });

    for (const sub of visibleSubs) {
      walk(sub, [...path, sub.name()]);
    }
  }

  walk(program, []);
  return nodes;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escapeShellString(s: string): string {
  return s.replace(/'/g, "'\\''");
}

function escapeZsh(s: string): string {
  return s.replace(/[\[\]'":()\\]/g, '\\$&');
}

// ---------------------------------------------------------------------------
// Bash
// ---------------------------------------------------------------------------

function generateBash(nodes: CompletionNode[]): string {
  const root = nodes.find((n) => n.path.length === 0)!;
  const globalFlags = root.options.map((o) => o.long).filter(Boolean);

  const cases: string[] = [];

  for (const node of nodes) {
    const key = node.path.join('__');
    const words = [
      ...node.subcommands.map((s) => s.name),
      ...node.options.map((o) => o.long).filter(Boolean),
    ];
    // Inject global flags for non-root commands
    if (node.path.length > 0) {
      words.push(...globalFlags);
    }
    const unique = [...new Set(words)];
    cases.push(`    "${key}")\n      COMPREPLY=($(compgen -W "${unique.join(' ')}" -- "$cur"))\n      ;;`);
  }

  return `# bash completion for ud                            -*- shell-script -*-
# Generated by: ud completion -s bash

_ud_completions() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  local cmd=""

  # Build command path by skipping flags and the binary name
  for ((i=1; i<COMP_CWORD; i++)); do
    case "\${COMP_WORDS[i]}" in
      -*) ;;
      *)
        if [ -n "$cmd" ]; then
          cmd="\${cmd}__\${COMP_WORDS[i]}"
        else
          cmd="\${COMP_WORDS[i]}"
        fi
        ;;
    esac
  done

  case "$cmd" in
${cases.join('\n')}
    *)
      ;;
  esac
}

complete -o default -F _ud_completions ud
`;
}

// ---------------------------------------------------------------------------
// Zsh
// ---------------------------------------------------------------------------

function generateZsh(nodes: CompletionNode[]): string {
  const root = nodes.find((n) => n.path.length === 0)!;

  // Build global option args for _arguments
  // Generate separate entries for short and long forms to avoid zsh brace expansion issues
  const globalOptionArgs: string[] = [];
  for (const o of root.options) {
    const desc = escapeZsh(o.description);
    const suffix = o.takesArg ? ':' : '';
    if (o.short) {
      const excl = `(${o.short} ${o.long})`;
      globalOptionArgs.push(`'${excl}${o.short}[${desc}]${suffix}'`);
      globalOptionArgs.push(`'${excl}${o.long}[${desc}]${suffix}'`);
    } else {
      globalOptionArgs.push(`'${o.long}[${desc}]${suffix}'`);
    }
  }

  const functions: string[] = [];

  // Build a function for each node that has subcommands
  for (const node of nodes) {
    if (node.subcommands.length === 0) continue;

    const funcName = node.path.length === 0
      ? '_ud'
      : `_ud__${node.path.join('__')}`;

    const commandEntries = node.subcommands
      .map((s) => `    '${escapeShellString(s.name)}:${escapeZsh(s.description)}'`)
      .join('\n');

    // Build case entries for subcommands that themselves have children
    const caseEntries: string[] = [];
    for (const sub of node.subcommands) {
      const childNode = nodes.find(
        (n) =>
          n.path.length === node.path.length + 1 &&
          n.path[n.path.length - 1] === sub.name &&
          n.path.slice(0, -1).join('.') === node.path.join('.'),
      );
      if (childNode && childNode.subcommands.length > 0) {
        const childFunc = `_ud__${[...node.path, sub.name].join('__')}`;
        caseEntries.push(`        ${sub.name}) ${childFunc} ;;`);
      }
    }

    // Root function includes global options
    const optionLines = node.path.length === 0
      ? globalOptionArgs.map((a) => `    ${a} \\`).join('\n')
      : '';

    // Build the case block — always include subcmd for _describe, add args if there are children
    const caseParts: string[] = [
      '    subcmd)',
      "      _describe 'command' commands",
      '      ;;',
    ];
    if (caseEntries.length > 0) {
      caseParts.push(
        '    args)',
        '      case $line[1] in',
        ...caseEntries,
        '      esac',
        '      ;;',
      );
    }

    functions.push(`${funcName}() {
  local -a commands=(
${commandEntries}
  )
  local state line context
  typeset -A opt_args

  _arguments -C \\
${optionLines ? optionLines + '\n' : ''}    '1: :->subcmd' \\
    '*::arg:->args'

  case $state in
${caseParts.join('\n')}
  esac
}`);
  }

  return `#compdef ud
# Generated by: ud completion -s zsh

${functions.join('\n\n')}

compdef _ud ud
`;
}

// ---------------------------------------------------------------------------
// Fish
// ---------------------------------------------------------------------------

function generateFish(nodes: CompletionNode[]): string {
  const root = nodes.find((n) => n.path.length === 0)!;
  const lines: string[] = [
    '# fish completion for ud',
    '# Generated by: ud completion -s fish',
    '',
    '# Disable file completions by default',
    'complete -c ud -f',
    '',
    '# Helper: check if the command line matches a given subcommand path',
    'function __ud_using_command',
    '  set -l cmd (commandline -opc)',
    '  # Remove flags from the command line',
    '  set -l cleaned',
    '  for word in $cmd',
    '    if not string match -q -- "-*" $word',
    '      set cleaned $cleaned $word',
    '    end',
    '  end',
    '  set -l expected ud $argv',
    '  if test (count $cleaned) -ne (count $expected)',
    '    return 1',
    '  end',
    '  for i in (seq (count $expected))',
    '    if test "$cleaned[$i]" != "$expected[$i]"',
    '      return 1',
    '    end',
    '  end',
    '  return 0',
    'end',
    '',
  ];

  // Global options
  lines.push('# Global options');
  for (const opt of root.options) {
    const parts = ['complete -c ud'];
    if (opt.short) parts.push(`-s ${opt.short.replace('-', '')}`);
    if (opt.long) parts.push(`-l ${opt.long.replace(/^--/, '')}`);
    if (opt.description) parts.push(`-d '${escapeShellString(opt.description)}'`);
    if (opt.takesArg) parts.push('-r');
    lines.push(parts.join(' '));
  }
  lines.push('');

  // For each node with subcommands, generate completions
  for (const node of nodes) {
    if (node.subcommands.length === 0) continue;

    // For root: show subcommands only when no subcommand has been entered yet
    // For nested: use our helper to match the exact command path
    const allTopLevelSubs = root.subcommands.map((s) => s.name).join(' ');
    const condition = node.path.length === 0
      ? `not __fish_seen_subcommand_from ${allTopLevelSubs}`
      : `__ud_using_command ${node.path.join(' ')}`;

    lines.push(`# ${node.path.length === 0 ? 'Top-level' : node.path.join(' ')} subcommands`);
    for (const sub of node.subcommands) {
      const desc = escapeShellString(sub.description);
      lines.push(`complete -c ud -n "${condition}" -a "${sub.name}" -d '${desc}'`);
    }
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// PowerShell
// ---------------------------------------------------------------------------

function generatePowershell(nodes: CompletionNode[]): string {
  const root = nodes.find((n) => n.path.length === 0)!;
  const globalFlags = root.options.map((o) => o.long).filter(Boolean);

  const cases: string[] = [];

  for (const node of nodes) {
    const key = node.path.join('_');
    const items: string[] = [];

    for (const sub of node.subcommands) {
      const desc = sub.description.replace(/'/g, "''");
      items.push(`            [CompletionResult]::new('${sub.name}', '${sub.name}', [CompletionResultType]::ParameterValue, '${desc}')`);
    }

    const flags = node.path.length === 0
      ? node.options.map((o) => o.long).filter(Boolean)
      : [...node.options.map((o) => o.long).filter(Boolean), ...globalFlags];

    for (const flag of [...new Set(flags)]) {
      items.push(`            [CompletionResult]::new('${flag}', '${flag}', [CompletionResultType]::ParameterName, '')`);
    }

    if (items.length > 0) {
      cases.push(`        '${key}' {\n${items.join('\n')}\n        }`);
    }
  }

  return `# PowerShell completion for ud
# Generated by: ud completion -s powershell

Register-ArgumentCompleter -Native -CommandName ud -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    $cmd = @()
    for ($i = 1; $i -lt $words.Count; $i++) {
        if ($words[$i] -notlike '-*' -and $i -lt $words.Count - 1) {
            $cmd += $words[$i]
        }
    }
    $cmdPath = $cmd -join '_'

    $completions = switch ($cmdPath) {
${cases.join('\n')}
    }

    $completions | Where-Object {
        $_.CompletionText -like "$wordToComplete*"
    }
}
`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function generateCompletion(program: Command, shell: Shell): string {
  const nodes = walkCommandTree(program);

  switch (shell) {
    case 'bash':
      return generateBash(nodes);
    case 'zsh':
      return generateZsh(nodes);
    case 'fish':
      return generateFish(nodes);
    case 'powershell':
      return generatePowershell(nodes);
  }
}
